class_name Enums

enum BipedalBodyPart { FOOT_L, SHIN_L, QUAD_L, FOOT_R, SHIN_R, QUAD_R, HAND_L, FOREARM_L, ARM_L, HAND_R, FOREARM_R, ARM_R, SPINE_1, SPINE_2, SPINE_3, NECK, HEAD, UNKNOWN }
enum BipedalJoint { ANKLE_L, KNEE_L, HIP_L, ANKLE_R, KNEE_R, HIP_R, WRIST_L, ELBOW_L, CLAVICLE_L, WRIST_R, ELBOW_R, CLAVICLE_R, SPINE_1, SPINE_2, NECK, HEAD }